variable "env"{}
variable "db_instances"{}
variable "app_instances"{}
variable "web_instances"{}
variable "app_port"{}
variable "zone_id"{}
variable "domain_name"{}
variable "vault_token"{}
variable "component_name"{}