 name: Terraform infra provision
 on: [workflow_dispatch]
 jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 # checking out s
      - run: |
          make dev-apply token=""
